services:
  order_service:              # Use underscores instead of hyphens
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network

  inventory_service:          # Underscore for service name
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - my-network

  api_gateway:                # Underscore for service name
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge