version: '3.8'

services:
  order-service:
    build:
      context: .  # Build from the project root
      dockerfile: order-service/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env  # Load environment variables
    networks:
      - my-network

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge