version: '3.9'

services:
  order-service:
    build:
      context: ./order-service
    ports:
      - "8001:8080"
    depends_on:
      - inventory-service
    networks:
      - backend

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8002:8081"
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8000:8080"
    depends_on:
      - order-service
      - inventory-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
