version: '3.8'

services:
  inventory:
    build: ./inventory
    ports:
      - "8081:8081"

  order:
    build: ./order-service
    ports:
      - "8082:8082"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventory
      - order
