FROM golang:1.23.0


WORKDIR /app
COPY go.mod go.sum ./
RUN go mod tidy

COPY . ./
RUN go build -o api-gateway

# Final stage
FROM debian:bullseye-slim

WORKDIR /root/
COPY --from=builder /app/api-gateway .

EXPOSE 8080
CMD ["./api-gateway"]
