FROM golang:1.24.1-alpine AS builder

# Enable Go modules
ENV CGO_ENABLED=0 GO111MODULE=on

WORKDIR /app

# Copy go.mod and go.sum first to leverage Docker caching
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the application binary
RUN go build -o api-gateway ./cmd

# Final lightweight image
FROM alpine:latest

WORKDIR /app

# Copy the binary from the builder
COPY --from=builder /app/api-gateway .

# Run the app
CMD ["./api-gateway"]
