FROM golang:1.24.1

WORKDIR /app

# Copy go.mod and go.sum to leverage Docker layer caching
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the entire project
COPY . .

# Build the binary from the main.go inside cmd/
RUN go build -o inventory-service ./cmd

# Expose the service port (change if your app listens on another)
EXPOSE 8081

# Run the service
CMD ["./inventory-service"]
